# Change these first
owner: borderlessvr # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Publisher Production
    url: https://publisher.bvrdev.com/
  - name: Publisher Staging
    url: https://publisher-staging.bvrdev.com/
  - name: API
    url: https://api.bvrdev.com/
  - name: API Staging
    url: https://api-staging.bvrdev.com/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/110405723?s=96&v=4
  name: Borderless Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
